# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5BjQYhdD3j9rbZu5GFF3QHJVhSYIhAO
"""

import streamlit as st
import requests

# FastAPI backend URL
API_URL = "http://127.0.0.1:8000/chat"

st.set_page_config(page_title="AI Recruiter Bot", page_icon="🤖", layout="centered")

st.markdown("## 🤖 AI-Powered HR Chatbot")
st.markdown("Ask me about your ideal employee, and I’ll find the best matches!")

query = st.text_input("🔍 Enter your query:", placeholder="e.g. Someone with React and backend experience...")

top_k = st.slider("How many matches do you want?", min_value=1, max_value=10, value=3)

if st.button("Find Matches") and query.strip():
    with st.spinner("Thinking..."):
        try:
            response = requests.post(API_URL, json={"query": query, "top_k": top_k})
            if response.status_code == 200:
                answer = response.json()["response"]
                st.success("✅ Matches Found!")
                st.markdown(answer)
            else:
                st.error(f"❌ Error: {response.status_code} - {response.text}")
        except Exception as e:
            st.error(f"⚠️ Failed to connect to backend:\n{e}")